### ISSUE TITLE
Frame enqueuing failed

### ISSUE THREAD

**Issue by viartemev** [viartemev/the-white-rabbit#4]
```
Exception in thread "main" java.io.IOException: Frame enqueuing failed
        at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.<unknown>(Unknown Source)
        at com.rabbitmq.client.impl.nio.SocketChannelFrameHandlerState.<unknown>(Unknown Source)
        at com.rabbitmq.client.impl.nio.SocketChannelFrameHandler.<unknown>(Unknown Source)
        at com.rabbitmq.client.impl.AMQConnection.writeFrame(Unknown Source)
        at com.rabbitmq.client.impl.AMQCommand.transmit(Unknown Source)
        at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(Unknown Source)
        at com.rabbitmq.client.impl.AMQChannel.transmit(Unknown Source)
        at com.rabbitmq.client.impl.ChannelN.basicPublish(Unknown Source)
        at com.rabbitmq.client.impl.ChannelN.<unknown>(Unknown Source)
        at com.rabbitmq.client.impl.ChannelN.<unknown>(Unknown Source)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.<unknown>(Unknown Source)
        at com.viartemev.thewhiterabbit.channel.ConfirmChannel.basicPublish(Unknown Source)
        at com.viartemev.thewhiterabbit.publisher.ConfirmPublisher.publish(Unknown Source)
        at com.viartemev.thewhiterabbit.publisher.ConfirmPublisher$publish$2$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(Unknown Source)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source)
        at kotlinx.coroutines.DispatchedTask.run(Unknown Source)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt.<unknown>(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source)
        at kotlinx.coroutines.BuildersKt.<unknown>(Unknown Source)
        at com.viartemev.thewhiterabbit.samples.SimpleSenderKt.main(Unknown Source)
        Suppressed: com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=505, reply-text=UNEXPECTED_FRAME - expected content body, got non content body frame instead, class-id=60, method-id=40)
                at com.rabbitmq.utility.ValueOrException.getValue(Unknown Source)
                at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(Unknown Source)
                at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(Unknown Source)
                at com.rabbitmq.client.impl.ChannelN.close(Unknown Source)
                at com.rabbitmq.client.impl.ChannelN.close(Unknown Source)
                at com.rabbitmq.client.impl.ChannelN.close(Unknown Source)
                at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(Unknown Source)
                at com.viartemev.thewhiterabbit.channel.ConfirmChannel.close(Unknown Source)
                at kotlin.jdk7.AutoCloseableKt.closeFinally(Unknown Source)
                ... 1 more
        Suppressed: com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=505, reply-text=UNEXPECTED_FRAME - expected content body, got non content body frame instead, class-id=60, method-id=40)
                at com.rabbitmq.client.impl.AMQConnection.startShutdown(Unknown Source)
                at com.rabbitmq.client.impl.AMQConnection.close(Unknown Source)
                at com.rabbitmq.client.impl.AMQConnection.close(Unknown Source)
                at com.rabbitmq.client.impl.AMQConnection.close(Unknown Source)
                at com.rabbitmq.client.impl.AMQConnection.close(Unknown Source)
                at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.close(Unknown Source)
                at kotlin.io.CloseableKt.closeFinally(Unknown Source)
                ... 1 more
```

**Comment by viartemev** [comment]
This bug is not actual anymore.
