### ISSUE TITLE
Add JMH benchmark

### ISSUE THREAD

**Issue by viartemev** [viartemev/the-white-rabbit#88]
Add JHM benchmark and compare it with https://github.com/reactor/reactor-rabbitmq

**Comment by viartemev** [comment]
The White Rabbit results:
**Configuration**:
```
@Warmup(iterations = 5, time = 5, timeUnit = TimeUnit.SECONDS)
@Measurement(iterations = 1, time = 5, timeUnit = TimeUnit.SECONDS)
@Fork(value = 2)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MICROSECONDS)
@State(Scope.Benchmark)
```
`@Param("1", "10", "100", "1000", "10000")`

```
Benchmark                                         (numberOfMessages)  Mode  Cnt       Score   Error  Units
ConfirmPublisherBenchmark.sendWithPublishConfirm                   1  avgt    2    1114,410          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm                  10  avgt    2    1773,545          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm                 100  avgt    2   14561,437          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm                1000  avgt    2   86387,193          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm               10000  avgt    2  708145,127          us/op
```

**Comment by viartemev** [comment]
A link to Reactor RabbitMQ benchmark: https://github.com/reactor/reactor-rabbitmq/blob/master/src/jmh/java/reactor/rabbitmq/SenderBenchmark.java

**Comment by asm0dey** [comment]
@acogoluegnes we would like to ask you to review this test if you'll have time and desire. Critics is absolutely welcome.
Also if you'll find incorrect usage of anything rabbit-related — we will be happy to try to fix it

**Comment by acogoluegnes** [comment]
@asm0dey @viartemev Thanks for bringing up this topic.

Here are the results I got:

```
$ uname -a
Linux acogoluegnes-inspiron 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# JMH version: 1.21
# VM version: JDK 11.0.2, OpenJDK 64-Bit Server VM, 11.0.2+7-LTS

The White Rabbit

Benchmark                                         (numberOfMessages)  Mode  Cnt        Score   Error  Units
ConfirmPublisherBenchmark.sendWithPublishConfirm                   1  avgt    2      104.172          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm                  10  avgt    2      598.625          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm                 100  avgt    2     3845.833          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm                1000  avgt    2    36108.709          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm               10000  avgt    2   392132.353          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm              100000  avgt    2  4098567.349          us/op

Reactor RabbitMQ

Benchmark                                (nbMessages)  Mode  Cnt        Score   Error  Units
SenderBenchmark.sendWithPublishConfirms             1  avgt    2      678.301          us/op
SenderBenchmark.sendWithPublishConfirms            10  avgt    2     1122.558          us/op
SenderBenchmark.sendWithPublishConfirms           100  avgt    2     4809.979          us/op
SenderBenchmark.sendWithPublishConfirms          1000  avgt    2    39819.682          us/op
SenderBenchmark.sendWithPublishConfirms         10000  avgt    2   387274.332          us/op
SenderBenchmark.sendWithPublishConfirms        100000  avgt    2  4055719.579          us/op
```

The White Rabbit is faster for small number of messages (10-), maybe because Reactor RabbitMQ initializes a bunch of staff compared to the amount of actual processing. For higher number of messages, both libraries behave roughly the same.

Both libraries use the RabbitMQ Java client, so I guess it all comes down to the respective extra layer (Kotlin/Reactor) and the publish confirms handling.

Note I got a few errors when running the White Rabbit benchmarks:

```
# Run progress: 0.00% complete, ETA 00:06:00
# Fork: 1 of 2

119.738 us/op
# Warmup Iteration   2: 104.683 us/op
# Warmup Iteration   3: 103.852 us/op
# Warmup Iteration   4: 102.921 us/op
# Warmup Iteration   5: 102.284 us/op
Iteration   1: 103.689 us/opG [26s]
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 24 seconds more...>

Non-finished threads:

Thread[pool-4-thread-1,5,main]
  at java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
  at java.base@11.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
  at java.base@11.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
  at java.base@11.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
  at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
  at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
  at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base@11.0.2/java.lang.Thread.run(Thread.java:834)

Thread[DestroyJavaVM,5,main]


<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 19 seconds more...>

Non-finished threads:

Thread[pool-4-thread-1,5,main]
  at java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
  at java.base@11.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
  at java.base@11.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
  at java.base@11.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
  at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
  at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
  at java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base@11.0.2/java.lang.Thread.run(Thread.java:834)

Thread[DestroyJavaVM,5,main]


<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 14 seconds more...>

...

<shutdown timeout of 30 seconds expired, forcing forked VM to exit>
```

**Comment by acogoluegnes** [comment]
Gave another try after changing the publishing handling in Reactor RabbitMQ to use the same algorithm and data structure as in the White Rabbit:

```
The White Rabbit

Benchmark                                         (numberOfMessages)  Mode  Cnt        Score   Error  Units
ConfirmPublisherBenchmark.sendWithPublishConfirm                   1  avgt    2      104.172          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm                  10  avgt    2      598.625          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm                 100  avgt    2     3845.833          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm                1000  avgt    2    36108.709          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm               10000  avgt    2   392132.353          us/op
ConfirmPublisherBenchmark.sendWithPublishConfirm              100000  avgt    2  4098567.349          us/op

Benchmark                                (nbMessages)  Mode  Cnt        Score   Error  Units
SenderBenchmark.sendWithPublishConfirms             1  avgt    2      697.424          us/op
SenderBenchmark.sendWithPublishConfirms            10  avgt    2     1306.490          us/op
SenderBenchmark.sendWithPublishConfirms           100  avgt    2     4819.441          us/op
SenderBenchmark.sendWithPublishConfirms          1000  avgt    2    39597.671          us/op
SenderBenchmark.sendWithPublishConfirms         10000  avgt    2   373226.865          us/op
SenderBenchmark.sendWithPublishConfirms        100000  avgt    2  3900685.520          us/op
```

Pretty much the same conclusion for small number number of messages, but the White Rabbit publish confirms algorithm makes Reactor RabbitMQ a bit faster for large number of messages (10K+).

**Comment by asm0dey** [comment]
@acogoluegnes cool, may I see please changes you used in Reactor RabbitMQ? Just curious what was written better
Also any ideas on nature of those exceptions?

@viartemev I tend to think that it's the difference between Linux and Mac hosts. Will benchmark on my laptop too.

**Comment by acogoluegnes** [comment]
@asm0dey I pushed the changes https://github.com/reactor/reactor-rabbitmq/commit/9404592bc6d26a751fd2d2f9180c36b6c5998ae5

It may be due a thread that is spawned but no properly stopped. This doesn't happen in the Reactor RabbitMQ benchmark run on Linux, so it must something related to the White Rabbit library.

**Comment by asm0dey** [comment]
@acogoluegnes I'm happy to read that my idea on confirmed publication helps tour implementation too :)
